-- MySQL Workbench Synchronization
-- Generated: 2014-12-03 20:01
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: cta

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `timeline`.`events` 
CHANGE COLUMN `start_date` `start_date` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `end_date` `end_date` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `headline` `headline` VARCHAR(140) NULL DEFAULT NULL ,
CHANGE COLUMN `text` `text` VARCHAR(255) NULL DEFAULT NULL ;

ALTER TABLE `timeline`.`types` 
CHANGE COLUMN `idtype` `idtype` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `timeline`.`tags` 
CHANGE COLUMN `idtag` `idtag` INT(11) NOT NULL AUTO_INCREMENT ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
